# Generated by Django 5.0.6 on 2024-05-21 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=88)),
                ('pictures', models.ImageField(upload_to='salebox/pictures')),
                ('is_available', models.BooleanField()),
                ('description', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MixBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_name', models.CharField(max_length=88)),
                ('images', models.ImageField(upload_to='salebox/images')),
                ('is_available', models.BooleanField()),
                ('description_box', models.CharField(max_length=300)),
                ('box_price', models.IntegerField()),
                ('included_in_the_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salebox.product')),
            ],
        ),
    ]
